services:
  app:
    build: "."
    ports:
      - "3000:3000"

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "c0MplicatedP@ssword"
