default: &default
  adapter: sqlserver
  host: "127.0.0.1"
  port: 1433
  username: "sa"
  password: "c0MplicatedP@ssword"

development:
  <<: *default
  database: zip_uploader_development

test:
  <<: *default
  database: zip_uploader_test
